routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Admin
Route::group(['namespace' => 'Admin', 'middleware' => ['admin', 'auth'], 'prefix' => 'admin'], function () {

    //  Dashboard
    Route::get('dashboard', 'DashboardController@dashboard')->name('admin.dashboard');

    //    Student
    Route::resource('student', 'StudentController');
    Route::group(['prefix' => 'student'], function (){
        Route::get('archive/all', 'StudentController@archive')->name('student.archive');
        Route::get('booking/{student}', 'StudentController@addBooking')->name('student.add_booking');
        Route::get('calendar/{student}', 'StudentController@calendar')->name('student.calendar');

    });

    //   Teacher
    Route::resource('teacher', 'TeacherController');
    Route::group(['prefix' => 'teacher'], function (){
        Route::get('booking/{teacher}', 'TeacherController@addBooking')->name('teacher.add_booking');
        Route::get('calendar/{teacher}', 'TeacherController@calendar')->name('teacher.calendar');
    });

    //   Team
    Route::resource('team', 'TeamsController');

    //    Booking
    Route::resource('booking', 'BookingsController');
    Route::group(['prefix' => 'booking'], function () {
        Route::get('create/{type}', 'BookingsController@create')->name('booking.create');
        Route::post('storeStudent', 'BookingsController@storeStudent')->name('booking.storeStudent');
        Route::post('store', 'BookingsController@store')->name('booking.store');
        Route::match(['put', 'patch'], 'updateStudent/{id}', 'BookingsController@updateStudent')->name('booking.updateStudent');
        Route::get('calendar/all', 'BookingsController@calendar')->name('booking.calendar');
        Route::get('archive/all', 'BookingsController@archive')->name('booking.archive');
    });

    //  Course
    Route::resource('course', 'CourseController');

    //  Price
    Route::resource('price', 'PriceController');

    //    Plan
    Route::get('plan', function () {
        return view('admin.plan.plan');
    })->name('plan');


    Route::get('accounting/invoice', function () {
        return view('admin.invoice');
    })->name('invoice');

    Route::get('accounting/bill', function () {
        return view('admin.bill');
    })->name('bill');
});

//Student
Route::group(['namespace' => 'Student', 'middleware' => ['auth', 'student'], 'prefix' => 'student'], function () {

    // Dashboard
    Route::get('dashboard', 'StudentController@dashboard')->name('student.dashboard');

    // Proflie
    Route::get('profile', 'StudentController@profile')->name('student.profile');

    // Plan
    Route::get('plan', 'StudentController@plan')->name('student.plan');

    // Progress
    Route::get('progress', 'StudentController@progress')->name('student.progress');

    //  Bookings
    Route::get('booking', 'StudentController@booking')->name('student.booking');

    Route::get('booking/calendar', 'StudentController@calendar')->name('student.booking.calendar');

    //  Account
    Route::get('account', 'StudentController@account')->name('student.account');

    // Edit Student
    Route::match(['put', 'patch'], 'accountUpdate/{student}', 'StudentController@accountUpdate')->name('student.accountUpdate');

});

//Teacher
Route::group(['namespace' => 'Teacher', 'middleware' => ['auth', 'teacher'], 'prefix' => 'teacher'], function () {

    // Dashboard
    Route::get('dashboard', 'TeacherController@dashboard')->name('teacher.dashboard');

    // Proflie
    Route::get('profile', 'TeacherController@profile')->name('teacher.profile');

    //    Students
    Route::get('student', 'TeacherController@student')->name('teacher.student');

    //  Bookings
    Route::get('booking', 'TeacherController@booking')->name('teacher.booking');

    // Account
    Route::get('account', 'TeacherController@account')->name('teacher.account');

    //  Edit Teacher
    Route::match(['put', 'patch'], 'accountUpdate/{teacher}', 'TeacherController@accountUpdate')->name('teacher.accountUpdate');

    // Calendar
   Route::get('booking/calendar', 'TeacherController@calendar')->name('teacher.booking.calendar');

    // Plan
    Route::get('plan', 'TeacherController@plan')->name('teacher.plan');


});

Auth::routes();
Route::get('/', 'Auth\LoginController@showLoginForm')->name('index');

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/TeacherController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Contracts\TeachersContract;
use App\Contracts\UserDataContract;
use App\Contracts\BookingsContract;
use App\Contracts\TeamsContract;
use App\Contracts\UsersContract;
use App\Http\Controllers\Controller;
use App\Http\Requests\Teacher\TeacherCreateRequest;
use App\Http\Requests\Teacher\TeacherEditRequest;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Session;


class TeacherController extends Controller
{
    protected $usersRepo;
    protected $teachersRepo;
    protected $usersDataRepo;
    protected $teamsRepo;
    protected $bookingsRepo;

    /**
     * TeacherController constructor.
     * @param UsersContract $usersContract
     * @param TeachersContract $teachersContract
     * @param UserDataContract $userDataContract
     * @param TeamsContract $teamsContract
     * @param BookingsContract $bookingsContract
     */
    public function __construct(UsersContract $usersContract, TeachersContract $teachersContract, UserDataContract $userDataContract, TeamsContract $teamsContract, BookingsContract $bookingsContract)
    {
        $this->usersRepo = $usersContract;
        $this->teachersRepo = $teachersContract;
        $this->usersDataRepo = $userDataContract;
        $this->teamsRepo = $teamsContract;
        $this->bookingsRepo = $bookingsContract;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $teachers = $this->usersRepo->getAllTeachers();

        return view('admin.teacher.teacher', compact('teachers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.teacher.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  TeacherCreateRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(TeacherCreateRequest $request)
    {
        $request = $request->except(['_token']);
        try {
            DB::beginTransaction();
            $newTeacher = $this->teachersRepo->store($request);
            $this->teachersRepo->userIdAttache($newTeacher, $request['data']);
            DB::commit();

            return redirect(route('teacher.index'))->with('success', 'Teacher Created successfully!');
        } catch (\Exception $exception) {
            Session::flash('error', $exception->getMessage());
            DB::rollBack();

            return redirect()->back();
        }
    }

    /**
     * @param User $teacher
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(User $teacher)
    {
        $teams = $this->teamsRepo->getTeamByTeacherId($teacher->id);

        return view('admin.teacher.show', compact('teacher', 'teams'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $teacher
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(User $teacher)
    {
        return view('admin.teacher.edit', compact('teacher'));
    }


    /**
     * @param TeacherEditRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(TeacherEditRequest $request, $id)
    {
        $request = $request->inputs();

        try {
            DB::beginTransaction();
            $this->teachersRepo->update($id,$request);
            $this->usersDataRepo->update($id, $request['data']);
            DB::commit();
        } catch (\Exception $exception) {
            Session::flash('error', $exception->getMessage());
            DB::rollBack();

            return redirect()->back();
        }

        return redirect(route('teacher.index'))->with('success', 'Teacher Edited successfully!');

    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $this->teachersRepo->destroy($id);
        return redirect()->back();
    }

    /**
     *
     * Create Booking
     *
     * @param User $teacher
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function addBooking(User $teacher)
    {
        $types = $this->bookingsRepo->bookingTypes()->pluck('name', 'name')->prepend('-- Select Type --', '');
        $students = $this->usersRepo->getAllStudents()->pluck('name', 'id')->prepend('-- Select Student --', '');

        return view('admin.teacher.booking', compact('teacher', 'types', 'students'));
    }

    /**
     * Show Bookings In Calendar
     *
     * @param User $teacher
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function calendar(User $teacher)
    {
        $bookings = $this->bookingsRepo->getByTeacherId($teacher->id);

        return view('admin.teacher.calendar', compact('teacher', 'bookings'));
    }

}

app/Http/Controllers/Teacher/TeacherController.php
<?php

namespace App\Http\Controllers\Teacher;

use App\Contracts\TeachersContract;
use App\Http\Controllers\Controller;
use App\Http\Requests\Teacher\TeacherEditRequest;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Session;
use Illuminate\Support\Facades\Auth;
use App\Contracts\UsersContract;
use App\Contracts\UserDataContract;
use App\Contracts\BookingsContract;

class TeacherController extends Controller
{
    protected $usersRepo;
    protected $userDataRepo;
    protected $bookingRepo;
    protected $teacherRepo;

    /**
     * StudentController constructor.
     * @param UsersContract $usersContract
     * @param UserDataContract $userDataContract
     * @param BookingsContract $bookingsContract
     * @param TeachersContract $teachersContract
     */
    public function __construct(TeachersContract $teachersContract,UsersContract $usersContract, UserDataContract $userDataContract, BookingsContract $bookingsContract)
    {
        $this->usersRepo = $usersContract;
        $this->userDataRepo = $userDataContract;
        $this->bookingRepo = $bookingsContract;
        $this->teacherRepo = $teachersContract;
    }
    /**
     * Teacher Dashboard
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function dashboard()
    {
        $user = Auth::user();
        $bookings = $this->bookingRepo->getByTeacherId($user->id);

        return view('teacher.dashboard', compact('bookings'));
    }
    /**
     * Teacher Profile
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function profile()
    {
        $user = Auth::user();
        $user->load('data', 'teamTeacher');

        return view('teacher.profile', compact('userData', 'user'));
    }

    /**
     * Teacher Students
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function student()
    {
        $user = Auth::user();
        $students = $this->usersRepo->getByParentId($user->id);

        return view('teacher.student', compact('students'));
    }

    /**
     * Teacher Booking
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function booking()
    {
        $user = Auth::user();
        $bookings = $this->bookingRepo->getByTeacherId($user->id);

        return view('teacher.booking', compact('bookings', 'user'));
    }

    /**
     * Teacher Lection Plan
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function plan()
    {
        return view('teacher.plan');
    }

    /**
     * Teacher Account Settings
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function account()
    {
        $user = Auth::user();

        return view('teacher.account', compact('user'));
    }

    /**
     * @param TeacherEditRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function accountUpdate(TeacherEditRequest $request, $id)
    {
        $user = Auth::user();

        if (Hash::check($request['old_password'], $user->password)){

            if ($request->new_password == $request->password){

                $request = $request->inputs();

                try {
                    DB::beginTransaction();
                    $this->teacherRepo->update($id,$request);
                    $this->userDataRepo->update($id, $request['data']);
                    DB::commit();
                } catch (\Exception $exception) {
                    Session::flash('error', $exception->getMessage());
                    DB::rollBack();

                    return redirect()->back();
                }
                return redirect(route('teacher.profile'))->with('success', 'Your Data Edited successfully!');
            } else {
                Session::flash('error', 'Passwords do not match');

                return redirect()->back();
            }
        } else {
            Session::flash('error', 'Old password does not match');

            return redirect()->back();
        }
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function calendar()
    {
        $user = Auth::user();
        $bookings = $this->bookingRepo->getByTeacherId($user->id);

        return view('teacher.calendar', compact('bookings'));
    }
}

resources/views/admin/teacher/booking.blade.php
@extends('layouts.app')
@section('content')
    @include('admin.layouts.sidebar')

    <div class="page-content-wrapper">
        <!-- BEGIN CONTENT BODY -->
        <div class="page-content">
            <!-- BEGIN PAGE HEADER-->
            <!-- BEGIN PAGE TITLE-->
            <h1 class="page-title"> Add Booking to teacher
            </h1>
            <div class="row">
                <div class="col-md-12 ">
                    <!-- BEGIN SAMPLE FORM PORTLET-->
                    <div class="portlet light bordered">
                        {{ Form::open([ 'route' => 'booking.store',  'class' => 'form-group',  'id' => 'form_sample_2'])}}
                        @include('admin.teacher._partials._booking', ['button_label' => 'Save'])
                        {{Form::close()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/teacher/calendar.blade.php
@extends('layouts.app')
@section('content')

    @include('admin.layouts.sidebar')
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <!-- BEGIN CONTENT BODY -->
        <div class="page-content">
            <!-- BEGIN PAGE HEADER-->
            <!-- BEGIN PAGE TITLE-->
            <h1 class="page-title">Your Booking</h1>
            <div class="col-md-10"><br>
                <a href="{{route('teacher.index')}}" class="btn btn-default"><i class="fa fa-long-arrow-left"></i> Back To Teachers</a>
                <a href="{{route('teacher.show', $teacher->id)}}" class="btn btn-info"><i class="fa fa-user"></i> View Teacher</a>
                <a href="{{route('teacher.edit', $teacher->id)}}" class="btn btn-info"><i class="fa fa-edit"></i> Edit Teacher</a>
                <br><br>
                <a href="{{route('teacher.add_booking', $teacher->id)}}" class="btn btn-info"><i class="fa fa-plus"></i> Add Booking</a>
            </div>

            <div class="portlet light calendar bordered">

                <div class="portlet-body">
                    <div id="drivi-calendar"> </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@include('includes.calendar')

resources/views/admin/teacher/create.blade.php
@extends('layouts.app')
@section('content')
@include('admin.layouts.sidebar')
@include('includes.messages')
    <div class="page-content-wrapper">
        <!-- BEGIN CONTENT BODY -->
        <div class="page-content">
            <!-- BEGIN PAGE HEADER-->
            <!-- BEGIN PAGE TITLE-->
            <h1 class="page-title"> Tilføj ny
            </h1>
            <div class="row">
                <div class="col-md-12 ">
                    <!-- BEGIN SAMPLE FORM PORTLET-->
                    <div class="portlet light bordered">
                        <div class="portlet-title">
                            <div class="caption font-red-sunglo">

                                <a href="{{route('teacher.index')}}" class="btn btn-default caption-subject bold uppercase"> <i class="fa fa-long-arrow-left"></i> Back to Lærer</a>
                            </div>
                        </div>
                        <div class="portlet-body ">
                            {{ Form::open([ 'route' => 'teacher.store',  'class' => 'form-group',  'id' => 'form_sample_2'])}}
                            @include('admin.teacher._partials._form', ['button_label' => 'Save'])
                            {{Form::close()}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/teacher/edit.blade.php
@extends('layouts.app')
@section('content')
@include('admin.layouts.sidebar')

<div class="page-content-wrapper">
    <div class="page-content">
        <h1 class="page-title">  Tilføj ny</h1>
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="col-md-9">
                    <a href="{{route('teacher.index')}}" class="btn btn-default"> <i class="fa fa-long-arrow-left"></i> Back to Teachers</a>
                    <a href="{{route('teacher.show', $teacher->id)}}" class="btn btn-info"><i class="fa fa-user"></i> View Teacher</a>
                    <br><br>
                    <a href="{{route('teacher.add_booking', $teacher->id)}}" class="btn btn-info"> <i class="fa fa-plus"></i>Add Booking</a>
                </div>
                <div class="col-md-3">
                    <a href="{{route('teacher.calendar', $teacher->id)}}" class="caption-subject bold uppercase btn btn-info"> <i class="fa fa-calendar-o"></i> Bookings</a>
                </div>
            </div>
        </div>
        <div class="portlet-body ">
            {!! Form::model($teacher, ['url' => route('teacher.update', $teacher->id), 'id' => 'form_sample_2', 'method' => 'PUT']) !!}
            @include('admin.teacher._partials._form', ['button_label' => 'Edit'])
            {!! Form::close() !!}
        </div>
    </div>
</div>

@endsection

resources/views/admin/teacher/show.blade.php
@extends('layouts.app')
@section('content')
    @include('admin.layouts.sidebar')
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <!-- BEGIN CONTENT BODY -->
        <div class="page-content">
           <div class="col-md-10">
               <a href="{{route('teacher.index')}}" class="btn btn-default"><i class="fa fa-long-arrow-left"></i> Back To Teachers</a>
               <a href="{{route('teacher.edit', $teacher->id)}}" class="btn btn-info"><i class="fa fa-edit"></i> Edit Teacher</a>
               <br><br>
               <a href="{{route('teacher.add_booking', $teacher->id)}}" class="btn btn-info"><i class="fa fa-plus"></i> Add Booking</a>
           </div>
            <div class="col-md-2"><a href="{{route('teacher.calendar', $teacher->id)}}" class="btn btn-info"><i class="fa fa-calendar-plus-o"></i> Bookings</a></div>
            <div class="col-md-6"><br><br>
                <!-- BEGIN SAMPLE TABLE PORTLET-->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">Teacher information</div>
                    </div>
                    <div class="portlet-body">
                        <div class="table-scrollable">
                            <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th> First Name </th>
                                    <th> Last Name </th>
                                    <th> Phone </th>
                                    <th> Email	 </th>
                                    <th> Address	 </th>
                                    <th> Address2	 </th>
                                    <th> Zip	 </th>
                                    <th> City	 </th>
                                    <th> Commentary	 </th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td> {{$teacher->name}}</td>
                                    <td> {{$teacher->data->last_name}} </td>
                                    <td> {{$teacher->data->phone}} </td>
                                    <td> {{$teacher->email}} </td>
                                    <td> {{$teacher->data->address}} </td>
                                    <td> {{$teacher->data->address2}} </td>
                                    <td> {{$teacher->data->city}} </td>
                                    <td> {{$teacher->data->post_index}} </td>
                                    <td> {{$teacher->data->description}} </td>

                                </tr>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- END SAMPLE TABLE PORTLET-->
            </div>
            <div class="col-md-6"><br><br>
                <!-- BEGIN SAMPLE TABLE PORTLET-->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">Elev liste</div>
                    </div>
                    <div class="portlet-body">
                        <div class="table-scrollable">
                            <table class="table table-striped table-hover">
                                @foreach($teams as $team)
                                   <h3> {{$team->name}}</h3>
                                    @foreach($team->students as $student)
                                       <a href="{{route('student.show', $student->id)}}" target="_blank"> {{$student->name}}<br></a>
                                    @endforeach
                                @endforeach
                            </table>
                        </div>
                    </div>
                </div>
                <!-- END SAMPLE TABLE PORTLET-->
            </div>
        </div>
    </div>
    @endsection

resources/views/admin/teacher/teacher.blade.php
@extends('layouts.app')
@section('content')
    @include('admin.layouts.sidebar')
    <div class="page-content-wrapper">
        <!-- BEGIN CONTENT BODY -->
        <div class="page-content">
            <!-- BEGIN PAGE HEADER-->
            <!-- BEGIN PAGE TITLE-->
            <h1 class="page-title"> Lærer
            </h1>
            <!-- END PAGE TITLE-->
            <!-- END PAGE HEADER-->
            <div class="row">
                <div class="col-md-12">
                    <!-- BEGIN EXAMPLE TABLE PORTLET-->
                    <div class="portlet light portlet-fit bordered">
                        <div class="portlet-body">
                            <div class="table-toolbar">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="btn-group">
                                            <a href="{{route('teacher.create')}}" class="btn green"> Create New
                                                <i class="fa fa-plus"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <table class="table datatable table-striped table-hover table-bordered" id="table">
                                <thead>
                                <tr>
                                    <th> NAVN </th>
                                    <th> EFTERNAVN </th>
                                    <th> TELEFON </th>
                                    <th> EMAIL </th>
                                    <th> Booking </th>
                                    <th> Delete </th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($teachers as $teacher)
                                <tr>
                                    <td><a href="{{route('teacher.show', $teacher->id)}}">{{$teacher->name}}</a> </td>
                                    <td><a href="{{route('teacher.show', $teacher->id)}}"> {{$teacher->data->last_name}} </a></td>
                                    <td><a href="{{route('teacher.show', $teacher->id)}}">{{$teacher->data->phone}} </a></td>
                                    <td><a href="{{route('teacher.show', $teacher->id)}}">{{$teacher->email}} </a></td>
                                    <td>
                                        <a href="{{route('teacher.calendar', $teacher->id)}}"> <i class="fa fa-calendar-plus-o"></i> </a>
                                    </td>
                                    <td>
                                        {!! Form::open(['url' => route('teacher.destroy',$teacher->id), 'id' => 'delete-form-'.$teacher->id, 'method' => 'DELETE', 'style' => 'display: none']) !!}
                                        {{Form::close()}}
                                        <a href="#teacher-{{$teacher->id}}" data-toggle="modal" > <i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                                <div class="modal fade draggable-modal" id="teacher-{{$teacher->id}}"  tabindex="-1" role="basic" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                            </div>
                                            <div class="modal-body"> Are you sure, You Want to delete {{$teacher->name}}? </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn dark btn-outline" data-dismiss="modal">Close</button>
                                                <a onclick="document.getElementById('delete-form-{{ $teacher->id }}').submit();" class="btn green">Delete</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- END EXAMPLE TABLE PORTLET-->
                </div>
            </div>
        </div>
        <!-- END CONTENT BODY -->
    </div>
@endsection
@include('includes.ordering')