routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Admin
Route::group(['namespace' => 'Admin', 'middleware' => ['admin', 'auth'], 'prefix' => 'admin'], function () {

    //  Dashboard
    Route::get('dashboard', 'DashboardController@dashboard')->name('admin.dashboard');

    //    Student
    Route::resource('student', 'StudentController');
    Route::group(['prefix' => 'student'], function (){
        Route::get('archive/all', 'StudentController@archive')->name('student.archive');
        Route::get('booking/{student}', 'StudentController@addBooking')->name('student.add_booking');
        Route::get('calendar/{student}', 'StudentController@calendar')->name('student.calendar');

    });

    //   Teacher
    Route::resource('teacher', 'TeacherController');
    Route::group(['prefix' => 'teacher'], function (){
        Route::get('booking/{teacher}', 'TeacherController@addBooking')->name('teacher.add_booking');
        Route::get('calendar/{teacher}', 'TeacherController@calendar')->name('teacher.calendar');
    });

    //   Team
    Route::resource('team', 'TeamsController');

    //    Booking
    Route::resource('booking', 'BookingsController');
    Route::group(['prefix' => 'booking'], function () {
        Route::get('create/{type}', 'BookingsController@create')->name('booking.create');
        Route::post('storeStudent', 'BookingsController@storeStudent')->name('booking.storeStudent');
        Route::post('store', 'BookingsController@store')->name('booking.store');
        Route::match(['put', 'patch'], 'updateStudent/{id}', 'BookingsController@updateStudent')->name('booking.updateStudent');
        Route::get('calendar/all', 'BookingsController@calendar')->name('booking.calendar');
        Route::get('archive/all', 'BookingsController@archive')->name('booking.archive');
    });

    //  Course
    Route::resource('course', 'CourseController');

    //  Price
    Route::resource('price', 'PriceController');

    //    Plan
    Route::get('plan', function () {
        return view('admin.plan.plan');
    })->name('plan');


    Route::get('accounting/invoice', function () {
        return view('admin.invoice');
    })->name('invoice');

    Route::get('accounting/bill', function () {
        return view('admin.bill');
    })->name('bill');
});

//Student
Route::group(['namespace' => 'Student', 'middleware' => ['auth', 'student'], 'prefix' => 'student'], function () {

    // Dashboard
    Route::get('dashboard', 'StudentController@dashboard')->name('student.dashboard');

    // Proflie
    Route::get('profile', 'StudentController@profile')->name('student.profile');

    // Plan
    Route::get('plan', 'StudentController@plan')->name('student.plan');

    // Progress
    Route::get('progress', 'StudentController@progress')->name('student.progress');

    //  Bookings
    Route::get('booking', 'StudentController@booking')->name('student.booking');

    Route::get('booking/calendar', 'StudentController@calendar')->name('student.booking.calendar');

    //  Account
    Route::get('account', 'StudentController@account')->name('student.account');

    // Edit Student
    Route::match(['put', 'patch'], 'accountUpdate/{student}', 'StudentController@accountUpdate')->name('student.accountUpdate');

});

//Teacher
Route::group(['namespace' => 'Teacher', 'middleware' => ['auth', 'teacher'], 'prefix' => 'teacher'], function () {

    // Dashboard
    Route::get('dashboard', 'TeacherController@dashboard')->name('teacher.dashboard');

    // Proflie
    Route::get('profile', 'TeacherController@profile')->name('teacher.profile');

    //    Students
    Route::get('student', 'TeacherController@student')->name('teacher.student');

    //  Bookings
    Route::get('booking', 'TeacherController@booking')->name('teacher.booking');

    // Account
    Route::get('account', 'TeacherController@account')->name('teacher.account');

    //  Edit Teacher
    Route::match(['put', 'patch'], 'accountUpdate/{teacher}', 'TeacherController@accountUpdate')->name('teacher.accountUpdate');

    // Calendar
   Route::get('booking/calendar', 'TeacherController@calendar')->name('teacher.booking.calendar');

    // Plan
    Route::get('plan', 'TeacherController@plan')->name('teacher.plan');


});

Auth::routes();
Route::get('/', 'Auth\LoginController@showLoginForm')->name('index');

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Team.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Team extends Model
{
    protected $table = 'teams';

    protected $fillable = [
        'id',
        'name',
        'description',
        'teacher_id',
        'student_id',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function students()
    {
        return $this->belongsToMany(User::class, 'team_student', 'team_id', 'student_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function teacher()
    {
        return $this->belongsTo(User::class, 'teacher_id');
    }
}

app/Http/Controllers/Admin/TeamsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Team;
use App\Http\Requests\Team\TeamCreateRequest;
use App\Contracts\TeamsContract;
use App\Contracts\UsersContract;
use Illuminate\Support\Facades\DB;

class TeamsController extends Controller
{

    protected $teamsRepo;
    protected $usersRepo;

    /**
     * TeamsController constructor.
     *
     * @param TeamsContract $teamsContract
     * @param UsersContract $usersContract
     */
    public function __construct(TeamsContract $teamsContract, UsersContract $usersContract)
    {
        $this->teamsRepo = $teamsContract;
        $this->usersRepo = $usersContract;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $teams = $this->teamsRepo->getAllTeams();

        return view('admin.team.team', compact('teams', 'teacher'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $teachers = $this->usersRepo->getAllTeachers()->pluck('name', 'id')->prepend('-- Select Teacher --', '');
        $students = $this->usersRepo->getAllStudents()->pluck('name', 'id');

        return view('admin.team.create', compact('teachers', 'students'));
    }

    /**
     * @param TeamCreateRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(TeamCreateRequest $request)
    {
        $studentIds = $request->get('student_id');
        $request = $request->inputs();

        try {
            DB::beginTransaction();
            $newTeam = $this->teamsRepo->store($request);
            $this->teamsRepo->teamStudentAttache($newTeam, $studentIds);
            DB::commit();
        } catch (\Exception $exception) {
            DB::rollBack();

            return redirect()->back();
        }

        return redirect(route('team.index'))->with('success', 'Team Created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     */
    public function show($id)
    {
        //
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param Team $team
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Team $team)
    {
        $teachers = $this->usersRepo->getAllTeachers()->pluck('name', 'id')->prepend('-- Select Teacher --', '');
        $students = $this->usersRepo->getAllStudents()->pluck('name', 'id');

        return view('admin.team.edit', compact('team', 'teachers', 'students'));
    }


    /**
     * @param TeamCreateRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(TeamCreateRequest $request, $id)
    {
        $studentIds = $request->get('student_id');
        $request = $request->inputs();

        try {
            DB::beginTransaction();

            $this->teamsRepo->update($id, $request);
            $team = Team::find($id);
            $team->students()->sync($studentIds);

            DB::commit();
        } catch (\Exception $exception) {
            dd($exception);
            DB::rollBack();

            return redirect()->back();
        }

        return redirect(route('team.index'))->with('success', 'Team Edited successfully!');
    }

    /**
     * @param $id
     * @param TeamsContract $teamRepo
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id, TeamsContract $teamRepo)
    {
        $teamRepo->destroy($id);
        return redirect()->back();
    }
}

resources/views/admin/team/create.blade.php
@extends('layouts.app')
@section('content')
    @include('admin.layouts.sidebar')
    <div class="page-content-wrapper">
        <!-- BEGIN CONTENT BODY -->
        <div class="page-content">
            <!-- BEGIN PAGE HEADER-->
            <!-- BEGIN PAGE TITLE-->
            <h1 class="page-title"> Tilføj ny team
            </h1>
            <div class="row">
                <div class="col-md-12 ">
                    <!-- BEGIN SAMPLE FORM PORTLET-->
                    <div class="portlet light bordered">
                        <div class="portlet-title">
                            <div class="caption font-red-sunglo">
                                <i class="fa fa-long-arrow-left"></i>
                                <a href="{{route('team.index')}}" class="caption-subject bold uppercase"> Back to Team</a>
                            </div>
                        </div>
                        <div class="portlet-body ">
                            {{ Form::open([ 'route' => 'team.store',  'class' => 'form-group',  'id' => 'form_sample_2', 'multiple'])}}
                            @include('admin.team._partials._form', ['button_label' => 'Save', 'teamSelectedStudents' => null])
                            {{Form::close()}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/team/edit.blade.php
@extends('layouts.app')
@section('content')
    @include('admin.layouts.sidebar')

    <div class="page-content-wrapper">
        <div class="page-content">
            <h1 class="page-title"> Rediger team
            </h1>
            <div class="row">
                <div class="col-md-12 ">
                    <!-- BEGIN SAMPLE FORM PORTLET-->
                    <div class="portlet light bordered">
                        <div class="portlet-title">
                            <div class="caption font-red-sunglo col-md-10">
                                <a href="{{route('team.index')}}" class="caption-subject bold uppercase btn btn-info"> <i class="fa fa-long-arrow-left"></i> Back to Team</a>
                            </div>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        {!! Form::model($team, ['url' => route('team.update', $team->id), 'id' => 'form_sample_2', 'method' => 'PUT']) !!}
                        @include('admin.team._partials._form', ['button_label' => 'Edit', 'teamSelectedStudents' => $team->students->pluck('id')])
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/team/team.blade.php
@extends('layouts.app')
@section('content')
    @include('admin.layouts.sidebar')
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <!-- BEGIN CONTENT BODY -->
        <div class="page-content">
            <!-- BEGIN PAGE HEADER-->
            <!-- BEGIN PAGE TITLE-->
            <h1 class="page-title"> Team
            </h1>
            <!-- END PAGE TITLE-->
            <!-- END PAGE HEADER-->
            <div class="row">
                <div class="col-md-12">
                    <!-- BEGIN EXAMPLE TABLE PORTLET-->
                    <div class="portlet light portlet-fit bordered">

                        <div class="portlet-body">
                            <div class="table-toolbar">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="btn-group">
                                            <a href="{{route('team.create')}}" class="btn green"> Create New
                                                <i class="fa fa-plus"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <table class="table table-striped table-hover table-bordered" id="table">
                                <thead>
                                <tr>
                                    <th>NAME </th>
                                    <th> MEMBERS </th>
                                    <th> Delete </th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($teams as $team)
                                <tr>
                                    <td><a href="{{route('team.edit', $team->id)}}">{{$team->name}}</a> </td>
                                    <td>
                                        <b>Lærer:</b> <a href="{{route('teacher.show', $team->teacher->id)}}"> {{$team->teacher->name}}</a> <br>
                                        <b>Elev:</b> @foreach($team->students as $student) <a href="{{route('student.show', $student->id)}}">{{$student->name}}, </a> @endforeach </td>
                                    <td>
                                        {!! Form::open(['url' => route('team.destroy',$team->id), 'id' => 'delete-form-'.$team->id, 'method' => 'DELETE', 'style' => 'display: none']) !!}
                                        {{Form::close()}}
                                        <a href="#team-{{$team->id}}" data-toggle="modal" > <i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                                <div class="modal fade draggable-modal" id="team-{{$team->id}}" tabindex="-1" role="basic" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                            </div>
                                            <div class="modal-body"> Are you sure, You Want to delete this? </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn dark btn-outline" data-dismiss="modal">Close</button>
                                                <a  type="button"   onclick=document.getElementById('delete-form-{{ $team->id }}').submit();
                                                        " class="btn green">Delete</a>
                                            </div>
                                        </div>
                                        <!-- /.modal-content -->
                                    </div>
                                    <!-- /.modal-dialog -->
                                </div>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- END EXAMPLE TABLE PORTLET-->
                </div>
            </div>
        </div>
        <!-- END CONTENT BODY -->
    </div>
    <!-- END CONTENT -->
    </div>
@endsection
@include('includes.ordering')