routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Admin
Route::group(['namespace' => 'Admin', 'middleware' => ['admin', 'auth'], 'prefix' => 'admin'], function () {

    //  Dashboard
    Route::get('dashboard', 'DashboardController@dashboard')->name('admin.dashboard');

    //    Student
    Route::resource('student', 'StudentController');
    Route::group(['prefix' => 'student'], function (){
        Route::get('archive/all', 'StudentController@archive')->name('student.archive');
        Route::get('booking/{student}', 'StudentController@addBooking')->name('student.add_booking');
        Route::get('calendar/{student}', 'StudentController@calendar')->name('student.calendar');

    });

    //   Teacher
    Route::resource('teacher', 'TeacherController');
    Route::group(['prefix' => 'teacher'], function (){
        Route::get('booking/{teacher}', 'TeacherController@addBooking')->name('teacher.add_booking');
        Route::get('calendar/{teacher}', 'TeacherController@calendar')->name('teacher.calendar');
    });

    //   Team
    Route::resource('team', 'TeamsController');

    //    Booking
    Route::resource('booking', 'BookingsController');
    Route::group(['prefix' => 'booking'], function () {
        Route::get('create/{type}', 'BookingsController@create')->name('booking.create');
        Route::post('storeStudent', 'BookingsController@storeStudent')->name('booking.storeStudent');
        Route::post('store', 'BookingsController@store')->name('booking.store');
        Route::match(['put', 'patch'], 'updateStudent/{id}', 'BookingsController@updateStudent')->name('booking.updateStudent');
        Route::get('calendar/all', 'BookingsController@calendar')->name('booking.calendar');
        Route::get('archive/all', 'BookingsController@archive')->name('booking.archive');
    });

    //  Course
    Route::resource('course', 'CourseController');

    //  Price
    Route::resource('price', 'PriceController');

    //    Plan
    Route::get('plan', function () {
        return view('admin.plan.plan');
    })->name('plan');


    Route::get('accounting/invoice', function () {
        return view('admin.invoice');
    })->name('invoice');

    Route::get('accounting/bill', function () {
        return view('admin.bill');
    })->name('bill');
});

//Student
Route::group(['namespace' => 'Student', 'middleware' => ['auth', 'student'], 'prefix' => 'student'], function () {

    // Dashboard
    Route::get('dashboard', 'StudentController@dashboard')->name('student.dashboard');

    // Proflie
    Route::get('profile', 'StudentController@profile')->name('student.profile');

    // Plan
    Route::get('plan', 'StudentController@plan')->name('student.plan');

    // Progress
    Route::get('progress', 'StudentController@progress')->name('student.progress');

    //  Bookings
    Route::get('booking', 'StudentController@booking')->name('student.booking');

    Route::get('booking/calendar', 'StudentController@calendar')->name('student.booking.calendar');

    //  Account
    Route::get('account', 'StudentController@account')->name('student.account');

    // Edit Student
    Route::match(['put', 'patch'], 'accountUpdate/{student}', 'StudentController@accountUpdate')->name('student.accountUpdate');

});

//Teacher
Route::group(['namespace' => 'Teacher', 'middleware' => ['auth', 'teacher'], 'prefix' => 'teacher'], function () {

    // Dashboard
    Route::get('dashboard', 'TeacherController@dashboard')->name('teacher.dashboard');

    // Proflie
    Route::get('profile', 'TeacherController@profile')->name('teacher.profile');

    //    Students
    Route::get('student', 'TeacherController@student')->name('teacher.student');

    //  Bookings
    Route::get('booking', 'TeacherController@booking')->name('teacher.booking');

    // Account
    Route::get('account', 'TeacherController@account')->name('teacher.account');

    //  Edit Teacher
    Route::match(['put', 'patch'], 'accountUpdate/{teacher}', 'TeacherController@accountUpdate')->name('teacher.accountUpdate');

    // Calendar
   Route::get('booking/calendar', 'TeacherController@calendar')->name('teacher.booking.calendar');

    // Plan
    Route::get('plan', 'TeacherController@plan')->name('teacher.plan');


});

Auth::routes();
Route::get('/', 'Auth\LoginController@showLoginForm')->name('index');

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/StudentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Contracts\StudentsContract;
use App\Contracts\UserDataContract;
use App\Contracts\UsersContract;
use App\Contracts\BookingsContract;
use App\Contracts\CourseContract;
use App\Contracts\PriceContract;
use App\Http\Controllers\Controller;
use App\Http\Requests\Student\StudentUpdateRequest;
use App\Models\User;
use App\Http\Requests\Student\StudentCreateRequest;
use Illuminate\Support\Facades\DB;
use Session;


class StudentController extends Controller
{
    protected $usersRepo;
    protected $usersDataRepo;
    protected $studentsRepo;
    protected $coursesRepo;
    protected $pricesRepo;
    protected $bookingRepo;

    /**
     * StudentController constructor.
     *
     * @param UsersContract $usersContract
     * @param StudentsContract $studentsContract
     * @param UserDataContract $userDataContract
     * @param CourseContract $courseContract
     * @param PriceContract $priceContract
     * @param BookingsContract $bookingsContract
     */
    public function __construct(BookingsContract $bookingsContract,UsersContract $usersContract, StudentsContract $studentsContract, UserDataContract $userDataContract, CourseContract $courseContract, PriceContract $priceContract)
    {
        $this->usersRepo = $usersContract;
        $this->studentsRepo = $studentsContract;
        $this->usersDataRepo = $userDataContract;
        $this->coursesRepo = $courseContract;
        $this->pricesRepo = $priceContract;
        $this->bookingRepo = $bookingsContract;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = $this->usersRepo->getAllStudents();

        return view('admin.student.student', compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $courses = $this->coursesRepo->getAllCourses()->pluck('name', 'id')->prepend('-- Select Course --', '');
        $prices = $this->pricesRepo->getAllPrices()->pluck('name', 'id')->prepend('-- Select Price --', '');
        $teachers = $this->usersRepo->getAllTeachers()->pluck('name', 'id')->prepend('-- Select Teacher --', '');

        return view('admin.student.create', compact('courses', 'prices', 'teachers'));
    }

    /**
     * @param StudentCreateRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(StudentCreateRequest $request)
    {
        $request = $request->except(['_token']);

        try {
            DB::beginTransaction();
            $newStudent = $this->studentsRepo->store($request);
            $this->studentsRepo->userIdAttache($newStudent, $request['data']);
            DB::commit();

            return redirect(route('student.index'))->with('success', 'Student Created successfully!');
        } catch (\Exception $exception) {
            Session::flash('error', $exception->getMessage());
            DB::rollBack();

            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param User $student
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(User $student)
    {
        $price = $this->pricesRepo->getById($student->data->course_price);
        $course = $this->coursesRepo->getById($student->data->course_type);

        return view('admin.student.show', compact('student', 'price', 'course'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $student
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(User $student)
    {
        $courses = $this->coursesRepo->getAllCourses()->pluck('name', 'id')->prepend('-- Select Course --', '');
        $prices = $this->pricesRepo->getAllPrices()->pluck('name', 'id')->prepend('-- Select Price --', '');
        $teachers = $this->usersRepo->getAllTeachers()->pluck('name', 'id')->prepend('-- Select Teacher --', '');

        return view('admin.student.edit', compact('student','courses', 'prices', 'teachers'));
    }

    /**
     * @param StudentUpdateRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(StudentUpdateRequest $request, $id)
    {
        $request = $request->inputs();

        try {
            DB::beginTransaction();
            $this->studentsRepo->update($id,$request);
            $this->usersDataRepo->update($id, $request['data']);
            DB::commit();
        } catch (\Exception $exception) {
            Session::flash('error', $exception->getMessage());
            DB::rollBack();

            return redirect()->back();
        }

        return redirect(route('student.index'))->with('success', 'Student Edited successfully!');
    }

    /**
     * @param $id
     * @param StudentsContract $studentRepo
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id, StudentsContract $studentRepo)
    {
        $studentRepo->destroy($id);

        return redirect()->route('student.index');
    }

    /**
     * @param $student
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function addBooking(User $student)
    {
        $types = $this->bookingRepo->bookingTypes()->pluck('name', 'name')->prepend('-- Select Type --', '');
        $teachers = $this->usersRepo->getAllTeachers()->pluck('name', 'id')->prepend('-- Select Teacher --', '');

        return view('admin.student.booking', compact('student', 'types', 'teachers'));
    }

    /**
     * Show Bookings In Calendar
     *
     * @param User $student
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function calendar(User $student)
    {
        $bookings = $this->bookingRepo->getByStudentId($student->id);

        return view('admin.student.calendar', compact('student', 'bookings'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function archive()
    {
        $students = $this->usersRepo->getArchiveStudents();

        return view('admin.student.archive', compact('students'));
    }

}

app/Http/Controllers/Student/StudentController.php
<?php

namespace App\Http\Controllers\Student;

use App\Http\Controllers\Controller;
use App\Contracts\UsersContract;
use App\Contracts\PriceContract;
use App\Contracts\StudentsContract;
use App\Contracts\TeamsContract;
use App\Contracts\CourseContract;
use App\Contracts\UserDataContract;
use App\Contracts\BookingsContract;
use App\Http\Requests\Student\StudentUpdateRequest;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Session;
use Illuminate\Support\Facades\Auth;

class StudentController extends Controller
{
    protected $usersRepo;
    protected $userDataRepo;
    protected $bookingRepo;
    protected $pricesRepo;
    protected $coursesRepo;
    protected $studentRepo;
    protected $teamsRepo;

    /**
     * StudentController constructor.
     * @param UsersContract $usersContract
     * @param UserDataContract $userDataContract
     * @param BookingsContract $bookingsContract
     * @param PriceContract $priceContract
     * @param CourseContract $courseContract
     * @param StudentsContract $studentsContract
     * @param TeamsContract $teamsContract
     */
    public function __construct(TeamsContract $teamsContract,StudentsContract $studentsContract,UsersContract $usersContract, UserDataContract $userDataContract, BookingsContract $bookingsContract, PriceContract $priceContract, CourseContract $courseContract)
    {
        $this->usersRepo = $usersContract;
        $this->userDataRepo = $userDataContract;
        $this->bookingRepo = $bookingsContract;
        $this->pricesRepo = $priceContract;
        $this->coursesRepo = $courseContract;
        $this->studentRepo = $studentsContract;
        $this->teamsRepo = $teamsContract;
    }

    /**
     * Student Dashboard
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function dashboard()
    {
        $user = Auth::user();
        $bookings = $this->bookingRepo->getByStudentId($user->id);

        return view('student.dashboard', compact('bookings'));
    }

    /**
     * Student Profile
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function profile()
    {
        $user = Auth::user();
        $user->load('data', 'parents', 'teams');

        return view('student.profile', compact( 'user'));
    }

    /**
     * Student Lection Plan
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function plan()
    {
        $user = Auth::user();
        $prices = $this->pricesRepo->getById($user->data->course_price);
        $courses = $this->coursesRepo->getById($user->data->course_type);

        return view('student.plan', compact('user', 'prices', 'courses'));

    }

    /**
     *Progress
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function progress()
    {
        $user = Auth::user();
        $teacher = $this->usersRepo->getById($user['parent_id']);

        return view('student.progress', compact('user', 'teacher'));
    }

    /**
     * Student Bookings
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function booking()
    {
        $user = Auth::user();
        $bookings = $this->bookingRepo->getByStudentId($user->id);

        return view('student.booking', compact('bookings'));
    }

    /**
     * Student Account Settings
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function account()
    {
        $user = Auth::user();

        return view('student.account', compact('user'));
    }


    /**
     * @param StudentUpdateRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function accountUpdate(StudentUpdateRequest $request, $id)
    {
        $user = Auth::user();

        if (Hash::check($request['old_password'], $user->password)){

            if ($request->new_password == $request->password){

                $request = $request->inputs();
                try {
                    DB::beginTransaction();
                    $this->studentRepo->update($id,$request);
                    $this->userDataRepo->update($id, $request['data']);
                    DB::commit();
                } catch (\Exception $exception) {
                    Session::flash('error', $exception->getMessage());
                    DB::rollBack();
                    return redirect()->back();
                }

                return redirect(route('student.profile'))->with('success', 'Your Data Edited successfully!');
            } else {
                Session::flash('error', 'Passwords do not match');

                return redirect()->back();
            }
        } else {
            Session::flash('error', 'Old password does not match');

            return redirect()->back();
        }

    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function calendar()
    {
        $user = Auth::user();
        $bookings = $this->bookingRepo->getByStudentId($user->id);

        return view('student.calendar', compact('bookings'));
    }
}

resources/views/admin/student/archive.blade.php
@extends('layouts.app')
@section('content')
    @include('admin.layouts.sidebar')
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <!-- BEGIN CONTENT BODY -->
        <div class="page-content">
            <!-- BEGIN PAGE HEADER-->
            <!-- BEGIN PAGE TITLE-->
            <h1 class="page-title"> Elev Archive
            </h1>
            <!-- END PAGE TITLE-->
            <!-- END PAGE HEADER-->
            <div class="row">
                <div class="col-md-12">
                    <!-- BEGIN EXAMPLE TABLE PORTLET-->
                    <div class="portlet light portlet-fit bordered">

                        <div class="portlet-body">
                            <div class="table-toolbar">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="btn-group">
                                            <a href="{{route('student.create')}}"  class="btn green"> Create New<i class="fa fa-plus"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <table class="table table-striped table-hover table-bordered" id="sample_editable_1">
                                <thead>
                                <tr>
                                    <th> CPR NR. </th>
                                    <th> NAVN </th>
                                    <th> EFTERNAVN </th>
                                    <th> TELEFON </th>
                                    <th> EMAIL </th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($students as $student)
                                    <tr>
                                        <td>{{$student->data->code}} </td>
                                        <td>{{$student->name}}</td>
                                        <td>{{$student->data->last_name}} </td>
                                        <td>{{$student->data->phone}}</td>
                                        <td>{{$student->email}}</td>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- END EXAMPLE TABLE PORTLET-->
                </div>
            </div>
        </div>
        <!-- END CONTENT BODY -->
    </div>
    <!-- END CONTENT -->
@endsection

resources/views/admin/student/booking.blade.php
@extends('layouts.app')
@section('content')
    @include('admin.layouts.sidebar')

    <div class="page-content-wrapper">
        <!-- BEGIN CONTENT BODY -->
        <div class="page-content">
            <!-- BEGIN PAGE HEADER-->
            <!-- BEGIN PAGE TITLE-->
            <h1 class="page-title"> Add Booking to student</h1>
            <div class="portlet light bordered">
                {{ Form::open([ 'route' => 'booking.store',  'class' => 'form-group',  'id' => 'form_sample_2'])}}
                @include('admin.student._partials._booking', ['button_label' => 'Save'])
                {{Form::close()}}
            </div>
        </div>
    </div>

@endsection

resources/views/admin/student/calendar.blade.php
@extends('layouts.app')
@section('content')

    @include('admin.layouts.sidebar')
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <!-- BEGIN CONTENT BODY -->
        <div class="page-content">
            <!-- BEGIN PAGE HEADER-->
            <!-- BEGIN PAGE TITLE-->
            <h1 class="page-title">Your Booking</h1>
            <div class="col-md-9"><br>
                <a href="{{route('student.index')}}" class="btn btn-default"><i class="fa fa-long-arrow-left"></i> Back To Students</a>
                <a href="{{route('student.show', $student->id)}}" class="btn btn-info"><i class="fa fa-user"></i> View Student</a>

                <a href="{{route('student.edit', $student->id)}}" class="btn btn-info"><i class="fa fa-edit"></i> Edit Student</a>
                <br><br>
                <a href="{{route('student.add_booking', $student->id)}}" class="btn btn-info"><i class="fa fa-plus"></i> Add Booking</a>
            </div>
            <div class="col-md-3"><br>
                <a href="" class="btn btn-info"><i class="fa fa-list-ul"></i> Lection Plan</a>
                <a href="#student-{{$student->id}}" data-toggle="modal" class="btn btn-warning"><i class="fa fa-book"></i> Archive </a>
                {!! Form::open(['url' => route('student.destroy',$student->id), 'id' => 'delete-form-'.$student->id, 'method' => 'DELETE', 'style' => 'display: none']) !!}
                {{Form::close()}}
                <div class="modal fade draggable-modal" id="student-{{$student->id}}"  tabindex="-1" role="basic" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            </div>
                            <div class="modal-body"> Are you sure you want to archive {{$student->name}}? </div>
                            <div class="modal-footer">
                                <button type="button" class="btn dark btn-outline" data-dismiss="modal">No</button>
                                <a onclick="document.getElementById('delete-form-{{ $student->id }}').submit();" class="btn green">Yes</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="portlet light calendar bordered">
                <div class="portlet-body">
                    <div id="drivi-calendar"> </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@include('includes.calendar')

resources/views/admin/student/edit.blade.php
@extends('layouts.app')
@section('content')
@include('admin.layouts.sidebar')

    <div class="page-content-wrapper">
        <div class="page-content">
            <h1 class="page-title"> Rediger Elev</h1>
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="col-md-9">
                        <a href="{{route('student.index')}}" class="btn btn-default"><i class="fa fa-long-arrow-left"></i> Back To Students</a>
                        <a href="{{route('student.show', $student->id)}}" class="btn btn-info"><i class="fa fa-user"></i> View Student</a>
                        <br><br>
                        <a href="{{route('student.add_booking', $student->id)}}" class="btn btn-info"><i class="fa fa-plus"></i> Add Booking</a>
                    </div>
                    <div class="col-md-3">
                        <a href="{{route('student.calendar', $student->id)}}" class="btn btn-info"><i class="fa fa-calendar-plus-o"></i> Bookings</a>
                        <a href="" class="btn btn-info"><i class="fa fa-list-ul"></i> Lection Plan</a><br><br>
                        <a href="#student-{{$student->id}}" data-toggle="modal" class="btn btn-warning"><i class="fa fa-book"></i> Archive </a>
                        {!! Form::open(['url' => route('student.destroy',$student->id), 'id' => 'delete-form-'.$student->id, 'method' => 'DELETE', 'style' => 'display: none']) !!}
                        {{Form::close()}}
                        <div class="modal fade draggable-modal" id="student-{{$student->id}}"  tabindex="-1" role="basic" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                    </div>
                                    <div class="modal-body"> Are you sure you want to archive {{$student->name}}? </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn dark btn-outline" data-dismiss="modal">No</button>
                                        <a onclick="document.getElementById('delete-form-{{ $student->id }}').submit();" class="btn green">Yes</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="portlet-body ">
                {!! Form::model($student, ['url' => route('student.update', $student->id), 'id' => 'form_sample_2', 'method' => 'PUT']) !!}
                    @include('admin.student._partials._form', ['button_label' => 'Edit'])
                {!! Form::close() !!}
            </div>
        </div>
        </div>
    </div>

@endsection

resources/views/admin/student/student.blade.php
@extends('layouts.app')
@section('content')
    @include('admin.layouts.sidebar')
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <!-- BEGIN CONTENT BODY -->
        <div class="page-content">
            <!-- BEGIN PAGE HEADER-->
            <!-- BEGIN PAGE TITLE-->
            <h1 class="page-title"> Elev
            </h1>
            <!-- END PAGE TITLE-->
            <!-- END PAGE HEADER-->
            <div class="row">
                <div class="col-md-12">
                    <!-- BEGIN EXAMPLE TABLE PORTLET-->
                    <div class="portlet light portlet-fit bordered">

                        <div class="portlet-body">
                            <div class="table-toolbar">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="btn-group">
                                            <a href="{{route('student.create')}}"  class="btn green"> Create New<i class="fa fa-plus"></i></a>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="btn-group pull-right">
                                            <a href="{{route('student.archive')}}"  class="btn blue btn-outline " ><i class="fa fa-archive"></i>Archive </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <table class="table table-striped table-hover table-bordered" id="table">
                                <thead>
                                <tr>
                                    <th> CPR NR. </th>
                                    <th> NAVN </th>
                                    <th> EFTERNAVN </th>
                                    <th> TELEFON </th>
                                    <th> EMAIL </th>
                                    <th> Booking </th>
                                    <th> Delete </th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($students as $student)
                                    <tr>
                                        <td><a href="{{route('student.show', $student->id)}} "> {{$student->data->code}} </a></td>
                                        <td><a href="{{route('student.show', $student->id)}}">{{$student->name}} </a></td>
                                        <td><a href="{{route('student.show', $student->id)}}">{{$student->data->last_name}} </a></td>
                                        <td><a href="{{route('student.show', $student->id)}}">{{$student->data->phone}} </a></td>
                                        <td><a href="{{route('student.show', $student->id)}}">{{$student->email}} </a></td>
                                        <td><a href="{{route('student.calendar', $student->id)}}"><i class="fa fa-calendar-plus-o"></i></a></td>
                                        <td>
                                            {!! Form::open(['url' => route('student.destroy',$student->id), 'id' => 'delete-form-'.$student->id, 'method' => 'DELETE', 'style' => 'display: none']) !!}
                                            {{Form::close()}}
                                            <a href="#student-{{$student->id}}" data-toggle="modal" > <i class="fa fa-trash"></i></a>
                                        </td>
                                    </tr>
                                    <div class="modal fade draggable-modal" id="student-{{$student->id}}"  tabindex="-1" role="basic" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                                </div>
                                                <div class="modal-body"> Are you sure, You Want to delete {{$student->name}}? </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn dark btn-outline" data-dismiss="modal">Close</button>
                                                    <a onclick="document.getElementById('delete-form-{{ $student->id }}').submit();" class="btn green">Delete</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- END EXAMPLE TABLE PORTLET-->
                </div>
            </div>
        </div>
        <!-- END CONTENT BODY -->
    </div>
    <!-- END CONTENT -->
    @endsection
@include('includes.ordering')